authors = ["Andrei Zhabinski <andrei.zhabinski@gmail.com>"]
name = "XGrad"
uuid = "f06b06aa-6afa-11e8-2a98-9d829055ec4f"
version = "0.2.0"

[deps]
Espresso = "f3367e62-6a9b-11e8-3ca8-97e71e02b39c"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
